FROM node

WORKDIR /app

COPY . /app

ENV YARN_CACHE_FOLDER=/usr/local/yarn-cache
VOLUME ./yarn-cache

RUN yarn install --silent

RUN yarn build

RUN yarn add -g serve

RUN serve build -l 5001

EXPOSE 5001