FROM node

WORKDIR /app

COPY . /app

ENV YARN_CACHE_FOLDER=/usr/local/yarn-cache
VOLUME ./yarn-cache

RUN yarn install --silent

RUN yarn build

RUN yarn global add serve

RUN serve -s build -l 5001

EXPOSE 5001