FROM node

WORKDIR /app

COPY . /app

ENV YARN_CACHE_FOLDER=/usr/local/yarn-cache
VOLUME ./yarn-cache

RUN yarn install --silent

CMD yarn start

RUN yarn add serve

RUN serve build -l 5001

EXPOSE 5001